config/routes.rb
Rails.application.routes.draw do
  root 'home#index'
  delete 'logout', to: 'home#logout'
  resources :users, only: [:create] do
    member do
      get :stats
    end
  end
  resources :games, only: [:new, :create, :show] do
    member do
      post :player_stop
      post :dealer_stop
    end
    resources :drawn_cards, only: [:create]
  end
  get 'leaderboards', to: 'leaderboards#index'
end

app/models/drawn_card.rb
class DrawnCard < ActiveRecord::Base
  include Deck
  validates_presence_of :game_id, :card_number
  validates_numericality_of :game_id, :card_number

  belongs_to :user
  belongs_to :game
end

app/models/game.rb
class Game < ActiveRecord::Base
  include BlackjackGame

  validates_presence_of :bet_amount, :user_id
  validates :bet_amount, numericality: { only_integer: true, greater_than: 0}

  belongs_to :user
  has_many :drawn_cards

  enum status: {pending: 'pending', won: 'won', drew: 'drew', lost: 'lost'}

  after_commit :draw_four_cards, on: :create

  #it is called as soon as the game starts allocates 2 cards to player and dealer alternatively
  def draw_four_cards
    cards = DrawnCard.first_four_cards
    cards.each_with_index do |card_number, index|
      if index%2 == 0 #player_cards
        self.drawn_cards.create({user_id: self.user_id, card_number: card_number})
      else #dealer cards
        self.drawn_cards.create({user_id: nil, card_number: card_number})
      end
    end
    self.check_for_stop self.user_id
  end

  #it draws one card and calls check for stop
  def draw_card(user_id)
    card_number = DrawnCard.draw_card(self.drawn_cards.pluck(:card_number))
    self.drawn_cards.create({user_id: user_id, card_number: card_number})
    self.check_for_stop user_id
  end

  #fetches card numbers from the db
  def card_numbers(user_id)
    self.drawn_cards.where(user_id: user_id).pluck(:card_number)
  end

  # calculates the score of the player or dealer in the game
  def calculate_score(user_id)
    Game.score(self.card_numbers user_id)
  end

  #it calculates scores of both dealer and player
  def scores
    return Game.score(self.card_numbers self.user_id), Game.score(self.card_numbers nil)
  end

  # this method checks for bust and forced stop for dealer
  def check_for_stop user_id
    p_score, d_score = self.scores
    score = p_score
    if user_id.nil?
      score = d_score
    end
    if Game.bust?(score)
      if user_id.nil?
        self.update_attributes({dealer_score: d_score, status: 'won', win_amount: (self.bet_amount*2)})
      else
        self.update_attributes({player_score: p_score, status: 'lost'})
      end
    elsif Game.max_score?(score)
      self.stop(user_id)
    elsif user_id.nil? and Game.forced_stop?(self.card_numbers(user_id))
      self.stop(user_id)
    elsif user_id.nil? and Game.can_stop?(self.card_numbers(user_id))
      user_game_status, blackjack = self.decision_maker(p_score, d_score, self.card_numbers(self.user_id).length, self.card_numbers(nil).length)
      if user_game_status == "lost"
        self.stop(user_id)
      end
    end

  end

  # this method stops the player or dealer if dealer stops then we get the result of the match and based on the result allocate money
  def stop(user_id)
    p_score, d_score = self.scores
    if user_id.present?
      self.update_attributes(player_score: p_score)
      check_for_stop nil #checks for the automatic stop of dealer.
    else
      user_game_status, blackjack = self.decision_maker(p_score, d_score, self.card_numbers(self.user_id).length, self.card_numbers(nil).length)
      win_amount = nil
      if user_game_status == 'won' and blackjack
        win_amount = 2.5*bet_amount
      elsif user_game_status == 'won'
        win_amount = 2*bet_amount
      end
      self.update_attributes(dealer_score: calculate_score(user_id), status: user_game_status, win_amount: win_amount)
    end
  end

  #checks if dealer can stop
  def dealer_stop?
    p_score, d_score = self.scores
    if Game.can_stop?(self.card_numbers nil) and d_score >= p_score
      true
    else
      false
    end
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  validates_presence_of :email
  validates_uniqueness_of :email
  validates_format_of :email, :with => /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\z/i

  has_many :games

  #pending
  def money_left
    won_amount = self.games.won.sum(:win_amount)
    lost_amount = self.games.lost.sum(:bet_amount)
    won_amount - lost_amount
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  rescue_from ActiveRecord::RecordNotFound, with: -> { error 404 }
  rescue_from Exceptions::UnauthorizedAccess, with: -> { error 401 }

  def current_user
    if session[:email].present?
      User.where(email: session[:email]).first
    else
      nil
    end
  end

  def auth_only!
    if current_user.blank?
      raise Exceptions::UnauthorizedAccess, 'Unauthorized'
    end
  end

  def auth_redirect!
    if current_user.present?
      redirect_to new_game_path
    end
  end

  def error status
    redirect_to "/#{status}.html"
  end
end

app/controllers/drawn_cards_controller.rb
class DrawnCardsController < ApplicationController
  before_action :auth_only!

  def create
    @game = Game.find(params[:game_id])
    if params[:dealer] == 'true' and @game.dealer_score.nil?
      @game.draw_card(nil)
      render 'dealer.js.erb'
    elsif @game.player_score.nil?
      @game.draw_card(current_user.id)
      render 'player.js.erb'
    else
      render :js => {}, status: 404
    end
  end

end

app/controllers/games_controller.rb
class GamesController < ApplicationController
  before_action :auth_only!
  before_action :set_game, only: [:player_stop, :dealer_stop]

  # it creates an instance of game with signed in user
  # renders the form in which the user is asked for bet amount
  def new
    @game = current_user.games.build()
  end

  # it shows the game with given id, only game owner can see.
  def show
    @game = Game.includes(:drawn_cards).where(id: params[:id]).first
    game_owner_only!
  end

  # it creates the game with bet_amount as params and user_id from current_user
  def create
    @game = current_user.games.build(game_params)
    if @game.save
      redirect_to @game
    else
      render :new
    end
  end

  # This action stands the user at particular score
  # saves the max possible score in the game
  def player_stop
    game_owner_only!
    @game.stop(current_user.id)
    redirect_to @game
  end

  # this action check for whether dealer can stop
  # if dealer can stop it stops the dealer
  def dealer_stop
    game_owner_only!
    if @game.dealer_stop?
      @game.stop(nil)
      redirect_to @game
    else
      redirect_to @game, alert: 'Dealer cannot stop before 17'
    end

  end

  private

  def game_params
    params.require(:game).permit(:bet_amount)
  end

  def set_game
    @game = Game.find(params[:id])
  end

  def game_owner_only!
    if @game.user_id != current_user.id
      raise Exceptions::UnauthorizedAccess, 'Unauthorized'
    end
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  before_action :auth_redirect!, only: [:index]

  def index

  end


  def logout
    session[:email] = nil
    redirect_to root_path
  end
end

app/controllers/leaderboards_controller.rb
class LeaderboardsController < ApplicationController
  before_action :auth_only!

  #user with most wins default
  def index
    @users = User.joins(:games).where(games: {status: 'won'}).group('users.id').order('count(games.*) DESC').select('users.*, count(games.*) as won_games').page(params[:page])
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :auth_redirect!, only: [:create]

  def create
    @user = User.find_or_create_by(email: user_params[:email])
    if(@user.errors.blank?)
      session[:email] = @user.email
      redirect_to find_game_path
    else
      redirect_to root_path, alert: 'Enter correct email'
    end
  end

  def stats
    @user = User.find(params[:id])
    @games = @user.games.where.not(status: 'pending').order('updated_at DESC')
  end

  private

  def user_params
    params.require(:user).permit(:email)
  end

  def find_game_path
    games = @user.games.order('created_at DESC')
    if games.first and games.first.pending?
      game_path(games.first)
    else
      new_game_path
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def current_user
    if session[:email].present?
      User.where(email: session[:email]).first
    else
      nil
    end
  end
end

app/views/drawn_cards/dealer.js.erb
$('.dealer-section').html('<%= j render(partial: "games/dealer", locals: {game: @game}) %>');
<% if !@game.pending? %>
$('.game-actions').html('<%= j render(partial: "games/game_actions", locals: {game: @game}) %>');
<% end %>

app/views/drawn_cards/player.js.erb
$('.player-section').html('<%= j render(partial: "games/player", locals: {game: @game}) %>');
<% if !@game.pending? %>
  $('.game-actions').html('<%= j render(partial: "games/game_actions", locals: {game: @game}) %>');
<% end %>
<% if @game.pending? and @game.player_score.present? %>
  window.location.reload();
<% end %>

app/views/games/_dealer.html.erb
<div class="dealer-cards">
  <%game.drawn_cards.order('id ASC').each_with_index do |card, index| %>
    <% if card.user_id.nil? %>
      <span class="label label-info" style="margin: 10px;display: inline-block;">
        <% if game.player_score.nil? and index == 3 %>
          XXXX
        <%else%>
          <%= card.card_name %>
        <% end %>
      </span>
    <% end %>
  <%end%>
</div>
<br/><br/>
<div class="dealer-actions clearfix">
  <% if game.pending? and game.player_score.present? and game.dealer_score.nil? %>
    <%= link_to 'Hit', game_drawn_cards_path(game, {dealer: true}), class: 'btn btn-success', 'data-method': 'post', :remote => true %>
    <% if game.dealer_stop? %>
      <%= link_to 'Stop', dealer_stop_game_path(game), class: 'btn btn-danger', 'data-method': 'post'%>
    <% end %>
  <% elsif game.dealer_score.present? %>
    <div class="label-warning label" style="display: inline-block;">
      <%= @game.dealer_score %>
    </div>
  <% end %>
</div>

app/views/games/_form.html.erb
<%= form_for game, :html => { :class => 'form-horizontal' } do |f| %>
  <% if game.errors.any? %>
    <ul class="alert-danger">
      <% game.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
    </ul>
  <% end %>
  <div class="form-group">
    <%= f.text_field :bet_amount, :class => 'text_field form-control', placeholder: '100' %>
  </div>
  <div class="form-group">
    <%= f.submit 'Start Game', :class => 'btn btn-primary' %>
    <%= link_to 'Statistics', stats_user_path(current_user), class: 'btn btn-warning' %>
  </div>
<% end %>

app/views/games/_game_actions.html.erb
<% if !@game.pending? %>
  <div class="text-center">
    <h3>
      <span class="label label-default">PLAYER <%= @game.status.upcase %></span>
    </h3>
    <br/>
    <%= link_to 'Deal Again', new_game_path, class: 'btn btn-primary' %>
    <%= link_to 'Statistics', stats_user_path(current_user), class: 'btn btn-success' %>
  </div>
<%end%>

app/views/games/_player.html.erb
<div class="player-cards clearfix">
  <%game.drawn_cards.each do |card| %>
    <% if card.user_id.present? %>
      <span class="label label-info" style="margin: 10px;    display: inline-block;">
        <%= card.card_name %>
      </span>
    <% end %>
  <%end%>
</div>
<br/><br/>
<div class="player-actions clearfix">
  <% if game.player_score.nil? %>
    <%= link_to 'Hit', game_drawn_cards_path(game), class: 'btn btn-success', 'data-method': 'post', :remote => true %>
    <%= link_to 'Stop', player_stop_game_path(game), class: 'btn btn-danger', 'data-method': 'post'%>
  <% else %>
    <div class="label-warning label" style="display: inline-block;">
      <%= @game.player_score %>
    </div>
  <% end %>
</div>

app/views/games/new.html.erb
<h3 class="text-center">Enter the Bet amount and Press on Start Game!</h3>
<br/><br/>
<div class="row">
  <div class="col-sm-2 col-xs-6 col-xs-offset-3 col-sm-offset-5">
    <%= render partial: 'games/form', locals: {game: @game}%>
  </div>
</div>

app/views/games/show.html.erb
<div class="col-xs-offset-1 col-xs-10 col-sm-5 col-sm-offset-1 text-center">
  <h1> DEALER </h1>
  <br/>
  <div class="dealer-section">
    <%= render partial: 'dealer', locals: {game: @game} %>
  </div>
</div>
<div class="col-xs-offset-1 col-xs-10 col-sm-5 col-sm-offset-0 text-center">
  <h1> PLAYER </h1>
  <br/>
  <div class="player-section">
    <%= render partial: 'player', locals: {game: @game} %>
  </div>
</div>
<div class="game-actions col-xs-offset-1 col-xs-10 text-center">
  <%= render partial: 'game_actions', locals: {game: @game} %>
</div>

app/views/home/index.html.erb
<h1 class="text-center">Welcome!</h1>
<h3 class="text-center">Start playing game by entering your email id</h3>
<br/><br/><br/>
<div class="row" style="background: white;">
  <div class="col-sm-4 col-sm-offset-4 col-xs-10 col-xs-offset-1 text-center">
    <%= render partial: 'users/form' %>
  </div>
</div>

app/views/layouts/_header.html.erb
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to 'BlackJack', root_path, class: 'navbar-brand' %>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav navbar-right">
        <% if current_user.present? %>
          <li><a class="bold"><%= current_user.money_left%></a></li>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false"><%= current_user.email %> <span class="caret"></span></a>
            <ul class="dropdown-menu">
              <li><%= link_to 'Logout', logout_path, 'data-method'=>'delete' %></li>
            </ul>
          </li>
        <% end %>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Blackjack</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<%= render partial: 'layouts/header', locals: {} %>
<%= yield %>

</body>
</html>

app/views/leaderboards/index.html.erb
<%= paginate @users %>
<div class="col-xs-12 col-xs-offset-0 col-sm-10 col-sm-offset-1">
  <%= link_to 'Statistics', stats_user_path(current_user), class: 'btn btn-warning pull-right' %>
  <%= link_to 'Start New Game', new_game_path, class: 'btn btn-primary pull-right' %>
  <h1 class="text-center"> Leaderboard </h1>
  <table class="table">
    <thead>
      <tr>
        <th class="text-center">User Email</th>
        <th class="text-center">NO OF WINS</th>
      </tr>
    </thead>
    <tbody>
    <% @users.each do |user| %>
      <tr>
        <td class="text-center">
          <%= link_to user.email, stats_user_path(user) %>
        </td>
        <td class="text-center">
          <%= user['won_games'] %>
        </td>
      </tr>
    <% end %>
    </tbody>
  </table>
</div>

app/views/users/_form.html.erb
<%= form_for User.new, :html => { :class => 'form-horizontal' } do |f| %>
  <% if flash[:alert] %>
    <ul class="alert-danger">
      <li><%= flash[:alert] %></li>
    </ul>
  <% end %>
  <div class="form-group">
    <%= f.text_field :email, :class => 'text_field form-control', type: 'email', placeholder: 'name@example.com' %>
  </div>
  <div class="form-group">
    <%= f.submit 'Go', :class => 'btn btn-primary' %>
  </div>
<% end %>

app/views/users/stats.html.erb
<div class="col-xs-12 col-xs-offset-0 col-sm-10 col-sm-offset-1">
  <%= link_to 'Leaderboard', leaderboards_path, class: 'btn btn-warning pull-right' %>
  <%= link_to 'Start New Game', new_game_path, class: 'btn btn-primary pull-right' %>
  <h1 class="text-center"> Statistics </h1>
  <table class="table">
    <thead> <tr> <th class="text-center">GAME #</th> <th class="text-center">PLAYER</th> <th class="text-center">DEALER</th> <th class="text-center">MONEY</th> </tr> </thead>
    <tbody>
    <% total = @games.length %>
    <% @games.each_with_index do |game, index| %>
      <tr class="<%= (game.won?) ? 'success' : ((game.drew?)? 'warning' : 'danger') %>">
        <td class="text-center">
          GAME <%= total - index %>
        </td>
        <td class="text-center">
          <%= game.player_score %>
        </td>
        <td class="text-center">
          <%= game.dealer_score %>
        </td>
        <td class="text-center">
          <%= (game.win_amount.to_i > 0) ? "+#{game.win_amount.to_i}" : "-#{game.bet_amount.to_i}"%>
        </td>
      </tr>
    <% end %>
    </tbody>
  </table>
</div>